name: Flask YouTube Downloader CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Celery worker
      run: |
        redis-server --daemonize yes  # Start Redis
        ./celery_worker.sh &  # Start Celery worker

    - name: Run Flask app tests
      run: |
        export FLASK_ENV=development
        flask run &
        sleep 5  # Wait for the server to start
        curl http://127.0.0.1:5000/  # Test the Flask server is up

    - name: Lint with flake8
      run: |
        pip install flake8
        # Run flake8 linting for syntax checks
        flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat warnings as errors
        flake8 app.py --count --exit-zero --max-line-length=127 --statistics
